# Generated by Django 4.1 on 2022-11-13 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='feeling1',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='feeling2',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='feeling3',
        ),
        migrations.AddField(
            model_name='answer',
            name='feeling',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='feeling', to='top.feeling', verbose_name='気持ち'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=100, null=True, verbose_name='回答'),
        ),
        migrations.AddField(
            model_name='answer',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='top.category', verbose_name='カテゴリ'),
        ),
    ]
