# Generated by Django 4.1.2 on 2022-10-22 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choice1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice1', to='top.choice'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='choice2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice2', to='top.choice'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='choice3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice3', to='top.choice'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
