# Generated by Django 4.1.2 on 2022-10-22 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0002_alter_answer_choice1_alter_answer_choice2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='choice4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice4', to='top.choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='choice5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice5', to='top.choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='choice6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice6', to='top.choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='choice7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice7', to='top.choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='choice8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice8', to='top.choice'),
        ),
    ]
