# Generated by Django 4.1 on 2022-12-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0002_category_remove_answer_feeling1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image_no',
            field=models.IntegerField(choices=[('1番', 1), ('2番', 2), ('3番', 3)], default=1, verbose_name='回答時に表示する画像番号'),
        ),
    ]
